name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.16.2
          args: release -f=goreleaser.yml --rm-dist --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/dist/**/referrer'
      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v2
        with:
          args: mod -licenses -json -output sbom.cdx.json
          version: v1
      - name: Attest Sbom
        uses: actions/attest-sbom@v1
        with:
          subject-path: '${{ github.workspace }}/dist/**/referrer'
          sbom-path: sbom.cdx.json
      - name: Attest custom predicate
        uses: actions/attest@v1
        with:
          subject-path: '${{ github.workspace }}/dist/**/referrer'
          predicate-type: 'https://example.com/my-predicate/v1'
          predicate: '{"hello": "world"}'
